services:
    api:
        image: '${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}'
        command: ["node", "dist/main"]
        env_file:
            - .env
        ports:
            - '4001:4001'
        network_mode: host
        environment:
            - NODE_ENV="${NODE_ENV}"
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped

    postgres:
        image: postgres:15-alpine
        env_file:
            - .env
        ports:
            - '5432:5432' # Same as POSTGRES_PORT
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks: []
        healthcheck:
            # test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            test: ['CMD-SHELL', 'true']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        env_file:
            - .env
        ports:
            - '6379:6379' # Same as REDIS_PORT
        command: redis-server --requirepass "${REDIS_PASSWORD}"
        volumes:
            - redis_data:/data
        networks: []
        healthcheck:
            test: redis-cli ping || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

volumes:
    redis_data:
    postgres_data:
# networks:
#     dannie-network:
#         driver: bridge
