import { type Options, RandomStringGenerator } from './random';

/**
 * A utility class for string manipulations and formatting.
 */
export class TextUtils {
    /**
     * Converts a camelCase or underscore-separated string to a title case format.
     * This method transforms camelCase and underscores into a readable format
     * with each word capitalized.
     *
     * For example:
     * - "myFirstName" becomes "My First Name"
     * - "my_first_name" becomes "My First Name"
     * - "P2P_Value" becomes "P2P Value"
     *
     * @param str - The string to be converted.
     * @returns The formatted string in title case.
     */
    static toTitleCase(str: string): string {
        let formattedString = str.replace(/([a-z])([A-Z])/g, '$1 $2');
        formattedString = formattedString.replace(/_/g, ' ');
        formattedString = formattedString.replace(/\b\w/g, (char) => char.toUpperCase());
        return formattedString;
    }

    /**
     * Normalizes a string by replacing invalid characters with an empty string
     * and converting spaces to underscores.
     *
     * For example:
     * - "first@name!" becomes "first_name"
     *
     * @param key - The string to be normalized.
     * @returns The normalized string with invalid characters removed and spaces replaced by underscores.
     */
    static normalize(key: string): string {
        const sanitizedKey = key.replace(/[^a-zA-Z0-9_ ]/g, '');
        return sanitizedKey.replace(/ /g, '_');
    }

    /**
     * Provides access to the RandomStringGenerator's random string generator function.
     *
     * @param options - The configuration options for the random string generation.
     * @returns A random string generated by the RandomStringGenerator.
     */
    static random(options?: Options): string {
        return RandomStringGenerator.generate(options);
    }

    /**
     * Converts a string to camelCase format.
     *
     * For example:
     * - "my_first_name" becomes "myFirstName"
     *
     * @param str - The string to be converted.
     * @returns The formatted string in camelCase
     */
    static toCamelCase(str: string): string {
        return str.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
    }

    /**
     * Sanitizes an IBAN by:
     * - Removing spaces and dashes.
     * - Converting all letters to uppercase.
     *
     * @param iban - The raw IBAN input from the user.
     * @returns A sanitized IBAN string (uppercase, without spaces or dashes).
     */
    static sanitizeIBAN(iban: string): string {
        return iban.replace(/[\s-]/g, '').toUpperCase();
    }

    /**
     * @param enm
     * @param value
     * @returns Enum equivalent of provided string
     */
    static stringToEnum<T>(theEnum: { [s: string]: T }, value: string): T | undefined {
        return (Object.values(theEnum) as unknown as string[]).includes(value) ? (value as unknown as T) : undefined;
    }

    static slugify(str: string): string {
        return str
            .normalize('NFKD')
            .replace(/[\u0300-\u036f]/g, '')
            .toLowerCase()
            .trim()
            .replace(/[\s_]+/g, '-')
            .replace(/[^a-z0-9-]/g, '')
            .replace(/-+/g, '-')
            .replace(/^-|-$/g, '');
    }
}
